export const TAGS_LIST = [
    { label: 'Adventure Seeker', value: 'adventureSeeker' },
    { label: 'Foodie', value: 'foodie' },
    { label: 'Globe Trotter', value: 'globeTrotter' },
    { label: 'Fitness Enthusiast', value: 'fitnessEnthusiast' },
    { label: 'Animal Lover', value: 'animalLover' },
    { label: 'Tech Geek', value: 'techGeek' },
    { label: 'Bookworm', value: 'bookworm' },
    { label: 'Music Lover', value: 'musicLover' },
    { label: 'Movie Buff', value: 'movieBuff' },
    { label: 'Art Lover', value: 'artLover' },
    { label: 'Fashionista', value: 'fashionista' },
    { label: 'Gamer', value: 'gamer' },
    { label: 'Yogi', value: 'yogi' },
    { label: 'Hiker', value: 'hiker' },
    { label: 'Coffee Connoisseur', value: 'coffeeConnoisseur' },
    { label: 'Wine Lover', value: 'wineLover' },
    { label: 'Beach Bum', value: 'beachBum' },
    { label: 'Pet Parent', value: 'petParent' },
    { label: 'DIY Enthusiast', value: 'diyEnthusiast' },
    { label: 'Entrepreneur', value: 'entrepreneur' },
    { label: 'Environmental Activist', value: 'environmentalActivist' },
    { label: 'Sports Fanatic', value: 'sportsFanatic' },
    { label: 'Photography Lover', value: 'photographyLover' },
    { label: 'Vegan', value: 'vegan' },
    { label: 'Spiritual Explorer', value: 'spiritualExplorer' },
    { label: 'Night Owl', value: 'nightOwl' },
    { label: 'Early Bird', value: 'earlyBird' },
    { label: 'Star Wars Fan', value: 'starWarsFan' },
    { label: 'Marvel Fan', value: 'marvelFan' },
    { label: 'Board Game Geek', value: 'boardGameGeek' },
    { label: 'Anime Lover', value: 'animeLover' },
    { label: 'Craft Beer Enthusiast', value: 'craftBeerEnthusiast' },
    { label: 'History Buff', value: 'historyBuff' },
    { label: 'Romantic', value: 'romantic' },
    { label: 'Adrenaline Junkie', value: 'adrenalineJunkie' },
    { label: 'Minimalist', value: 'minimalist' },
    { label: 'Sustainability Advocate', value: 'sustainabilityAdvocate' },
    { label: 'Fitness Freak', value: 'fitnessFreak' },
    { label: 'Gardener', value: 'gardener' },
    { label: 'Freelancer', value: 'freelancer' },
    { label: 'Musical Instrument Player', value: 'musicalInstrumentPlayer' },
    { label: 'Volunteer', value: 'volunteer' },
    { label: 'Podcast Junkie', value: 'podcastJunkie' },
    { label: 'Fashion Blogger', value: 'fashionBlogger' },
    { label: 'Podcaster', value: 'podcaster' },
    { label: 'Surfer', value: 'surfer' },
    { label: 'Skater', value: 'skater' },
];